/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hm_madroid_ecg_EcgFilter */

#ifndef _Included_com_hm_madroid_ecg_EcgFilter
#define _Included_com_hm_madroid_ecg_EcgFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hm_madroid_ecg_EcgFilter
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hm_madroid_ecg_EcgFilter_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_hm_madroid_ecg_EcgFilter
 * Method:    processEcg
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hm_madroid_ecg_EcgFilter_processEcg__I
  (JNIEnv *, jobject, jint);


#ifdef __cplusplus
}
#endif
#endif
